name: Docker Build and Test

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Check out the repo content

    - name: Build Docker image
      run: |
        cd docker
        docker build . -t mr-shortcut-image

    - name: Check if shortcutting node assign works
      run: |
        docker run --name mr_shortcut-container \
          --volume="$PWD:/root/catkin_ws/src/mr-shortcut" \
          mr-shortcut-image \
          -c "source /opt/ros/noetic/setup.bash && cd /root/catkin_ws && catkin build && source devel/setup.bash && timeout 60 roslaunch mr-shortcut dual_gp4.launch use_rviz:=false" > output.txt 2>&1 || true
        docker rm mr_shortcut-container
        if ! grep -q "Planning completed successfully" output.txt; then
          echo "Planning did not complete successfully"
          cat output.txt
          exit 1
        fi